server:
  port: 8081
#  context-path: /ui
#  session:
#    cookie:
#      name: UISESSION
#
#
#security:
#  basic:
#    enabled: false
#  oauth2:
#    client:
#      clientId: Ankesh
#      clientSecret: ankesh
#      accessTokenUri: http://localhost:8081/auth/oauth/token
#      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
#    resource:
#      userInfoUri: http://localhost:8081/groups/creategroups
#
#
#spring:
#  thymeleaf:
#    cache: false

security:
  oauth2:
    resource:
      jwt:
        key-value:
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyX1R29hQEkjAAsRVQGvK
          eXKgrF/kot7QvG5I7z+B8d8yZkuV97iQBf4SfJ/hRggvBZnDyRprHt4kw15jZoEJ
          dIQsR2OSBxXxaF6cYcNioWrOnThpnorhWUzWzjVDf3ubVIoGeB0/bP7WqvJaX0dr
          ai8P7s7fL20VW+8Ju2Q5MQ/zAB7ispOw8htwWD123sCF/CRrwVDTAcyfHQo2J3Uz
          yWeNOe4RZaP09MBVeyRQbnIU0NBRGov4Q3T2vjUQ0vwChlmy8lJiLm0SjUEKYKJu
          +7tLEvCEGXS0/mr9X1Jtnc9qybSvzPcSAI7sBgvcZ1f+ea3vFF0y9YJ7dEAgBpnL
          QQIDAQAB
          -----END PUBLIC KEY-----
