#server:
#  port: 8081
#  context-path: /ui
#  session:
#    cookie:
#      name: UISESSION
#
#
#security:
#  basic:
#    enabled: false
#  oauth2:
#    client:
#      clientId: Ankesh
#      clientSecret: ankesh
#      accessTokenUri: http://localhost:8081/auth/oauth/token
#      userAuthorizationUri: http://localhost:8081/auth/oauth/authorize
#    resource:
#      userInfoUri: http://localhost:8081/groups/creategroups
#
#
#spring:
#  thymeleaf:
#    cache: false